const ROOTS = {
  AUTH: '/auth',
  AUTH_DEMO: '/auth-demo',
  DASHBOARD: '/dashboard',
};

// ----------------------------------------------------------------------

export const paths = {
  banlao: {
    root: `/banlao`,
    history: '/banlao/history',

    architecture: {
      root: `/banlao/architecture`,
      details: (id: string) => `/banlao/architecture/${id}`,
    },
  },

  parents: {
    root: '/parents',
    luangPuSa: '/parents/luang-pu-sa',
    luangPuPramuan: '/parents/luang-pu-pramuan',
    sacred: {
      root: `/parents/sacred`,
      details: (id: string) => `/parents/sacred/${id}`,
    },
  },

  activity: {
    root: `/activity`,
    details: (id: string) => `/activity/${id}`,
  },

  fastival: {
    root: `/fastival`,
    details: (id: string) => `/fastival/${id}`,
  },

  article: {
    root: `/article`,

    blog: {
      root: '/article/blog',
      details: (id: string) => `/article/blog/${id}`,
    },

    dharma: {
      root: '/article/dharma',
      details: (id: string) => `/article/dharma/${id}`,
    },
  },

  // comingSoon: '/coming-soon',
  about: '/about-us',
  contact: '/contact-us',
  // faqs: '/faqs',
  page403: '/error/403',
  page404: '/error/404',
  page500: '/error/500',
  components: '/components',
  docs: '/docs',
  legal: {
    privacyPolicy: '/privacy-policy',
    serviceAgreement: '/service-agreement',
    termsOfService: '/terms-of-service',
  },
  // components: '/components',
  // docs: 'https://docs.minimals.cc',
  // changelog: 'https://docs.minimals.cc/changelog',
  // zoneUI: 'https://mui.com/store/items/zone-landing-page/',
  // minimalUI: 'https://mui.com/store/items/minimal-dashboard/',
  // freeUI: 'https://mui.com/store/items/minimal-dashboard-free/',
  // figma:
  //   'https://www.figma.com/file/hjxMnGUJCjY7pX8lQbS7kn/%5BPreview%5D-Minimal-Web.v5.4.0?type=design&node-id=0-1&mode=design&t=2fxnS70DuiTLGzND-0',

  auth: {
    amplify: {
      login: `${ROOTS.AUTH}/amplify/login`,
      verify: `${ROOTS.AUTH}/amplify/verify`,
      register: `${ROOTS.AUTH}/amplify/register`,
      newPassword: `${ROOTS.AUTH}/amplify/new-password`,
      forgotPassword: `${ROOTS.AUTH}/amplify/forgot-password`,
    },
    jwt: {
      login: `${ROOTS.AUTH}/login`,
      signIn: `${ROOTS.AUTH}/login`,
      register: `${ROOTS.AUTH}/register`,
      changePassword: `${ROOTS.AUTH}/change-password`,
    },
    firebase: {
      login: `${ROOTS.AUTH}/firebase/login`,
      verify: `${ROOTS.AUTH}/firebase/verify`,
      register: `${ROOTS.AUTH}/firebase/register`,
      forgotPassword: `${ROOTS.AUTH}/firebase/forgot-password`,
    },
    auth0: {
      login: `${ROOTS.AUTH}/auth0/login`,
    },
  },
  master: {
    root: '/master',
    school: { root: '/master/schools' },
    schoolAdmin: { root: '/master/school-admins' },
    subscriptionPlan: { root: '/master/subscription-plans' },
    systemFlow: '/master/system-flow',
  },
  admin: {
    root: ROOTS.DASHBOARD,
    guide: `${ROOTS.DASHBOARD}/guide`,
    announcements: `${ROOTS.DASHBOARD}/announcements`,
    lineNotifications: `${ROOTS.DASHBOARD}/line-notifications`,
    schoolHolidays: `${ROOTS.DASHBOARD}/school-holidays`,
    school: `${ROOTS.DASHBOARD}/school`,
    academicYear: { root: `${ROOTS.DASHBOARD}/academic-years` },
    classroom: { root: `${ROOTS.DASHBOARD}/classrooms` },
    subject: { root: `${ROOTS.DASHBOARD}/subjects` },
    enrollment: { root: `${ROOTS.DASHBOARD}/enrollments` },
    teacherAssignment: { root: `${ROOTS.DASHBOARD}/teacher-assignments` },
    scheduleBuilder: `${ROOTS.DASHBOARD}/schedule-builder`,
    scheduleSubmissions: `${ROOTS.DASHBOARD}/schedule-submissions`,
    scheduleApprovals: `${ROOTS.DASHBOARD}/schedule-approvals`,
    gradeReviews: `${ROOTS.DASHBOARD}/grade-reviews`,
    gradeResults: `${ROOTS.DASHBOARD}/grade-results`,
    documents: {
      root: `${ROOTS.DASHBOARD}/documents`,
      my: `${ROOTS.DASHBOARD}/documents/my`,
      templates: `${ROOTS.DASHBOARD}/documents/templates`,
    },
    user: { root: `${ROOTS.DASHBOARD}/users` },
    student: {
      root: `${ROOTS.DASHBOARD}/students`,
      importData: `${ROOTS.DASHBOARD}/students/import`,
      list: `${ROOTS.DASHBOARD}/students/list`,
    },
    department: { root: `${ROOTS.DASHBOARD}/departments` },
    accessPermissions: `${ROOTS.DASHBOARD}/access-permissions`,
    masterData: {
      staffTypes: `${ROOTS.DASHBOARD}/master-data/staff-types`,
      prefixes: `${ROOTS.DASHBOARD}/master-data/prefixes`,
      positions: `${ROOTS.DASHBOARD}/master-data/positions`,
      academicRanks: `${ROOTS.DASHBOARD}/master-data/academic-ranks`,
      employmentStatuses: `${ROOTS.DASHBOARD}/master-data/employment-statuses`,
      learningAreas: `${ROOTS.DASHBOARD}/master-data/learning-areas`,
      subjectTypes: `${ROOTS.DASHBOARD}/master-data/subject-types`,
      educationStages: `${ROOTS.DASHBOARD}/master-data/education-stages`,
    },
  },
  teacher: {
    root: '/teacher',
    profile: '/teacher/profile',
    guide: '/teacher/guide',
    school: '/teacher/school',
    department: '/teacher/department',
    assignments: '/teacher/assignments',
    students: '/teacher/students',
    attendanceScan: '/teacher/attendance-scan',
    timetable: '/teacher/timetable',
    announcements: '/teacher/announcements',
    departmentAcademicYear: { root: '/teacher/department/academic-years' },
    departmentClassroom: '/teacher/department/classrooms',
    departmentSubject: '/teacher/department/subjects',
    departmentEnrollment: { root: '/teacher/department/enrollments' },
    departmentAnnouncements: '/teacher/department/announcements',
    departmentStudent: '/teacher/department/students',
    departmentStaff: { root: '/teacher/department/staff' },
    scheduleBuilder: '/teacher/schedule-builder',
    scheduleSubmissions: '/teacher/schedule-submissions',
    scheduleApprovals: '/teacher/schedule-approvals',
    gradeReviews: '/teacher/grade-reviews',
    gradeResults: '/teacher/grade-results',
    documents: {
      root: '/teacher/documents',
      my: '/teacher/documents/my',
      templates: '/teacher/documents/templates',
    },
  },
  student: {
    root: '/student',
    profile: '/student/profile',
    classroom: '/student/classroom',
    subjects: '/student/subjects',
    assignments: '/student/assignments',
    attendance: '/student/attendance',
    timetable: '/student/timetable',
    qr: '/student/qr',
  },
  authDemo: {
    classic: {
      login: `${ROOTS.AUTH_DEMO}/classic/login`,
      register: `${ROOTS.AUTH_DEMO}/classic/register`,
      forgotPassword: `${ROOTS.AUTH_DEMO}/classic/forgot-password`,
      newPassword: `${ROOTS.AUTH_DEMO}/classic/new-password`,
      verify: `${ROOTS.AUTH_DEMO}/classic/verify`,
    },
    modern: {
      login: `${ROOTS.AUTH_DEMO}/modern/login`,
      register: `${ROOTS.AUTH_DEMO}/modern/register`,
      forgotPassword: `${ROOTS.AUTH_DEMO}/modern/forgot-password`,
      newPassword: `${ROOTS.AUTH_DEMO}/modern/new-password`,
      verify: `${ROOTS.AUTH_DEMO}/modern/verify`,
    },
  },
  // DASHBOARD
  dashboard: {
    root: ROOTS.DASHBOARD,
    activity: `${ROOTS.DASHBOARD}/activity`,
    activityNew: `${ROOTS.DASHBOARD}/activity/new`,
    activityEdit: (id: string) => `${ROOTS.DASHBOARD}/activity/${id}/edit`,
    architectures: `${ROOTS.DASHBOARD}/architectures`,
    architectureNew: `${ROOTS.DASHBOARD}/architectures/new`,
    architectureEdit: (id: string) => `${ROOTS.DASHBOARD}/architectures/${id}/edit`,
    banners: `${ROOTS.DASHBOARD}/banners`,
    bannerNew: `${ROOTS.DASHBOARD}/banners/new`,
    bannerEdit: (id: string) => `${ROOTS.DASHBOARD}/banners/${id}/edit`,
    blogs: `${ROOTS.DASHBOARD}/blogs`,
    blogNew: `${ROOTS.DASHBOARD}/blogs/new`,
    blogEdit: (id: string) => `${ROOTS.DASHBOARD}/blogs/${id}/edit`,
    contacts: `${ROOTS.DASHBOARD}/contacts`,
    dharmas: `${ROOTS.DASHBOARD}/dharmas`,
    dharmaNew: `${ROOTS.DASHBOARD}/dharmas/new`,
    dharmaEdit: (id: string) => `${ROOTS.DASHBOARD}/dharmas/${id}/edit`,
    festivals: `${ROOTS.DASHBOARD}/festivals`,
    festivalNew: `${ROOTS.DASHBOARD}/festivals/new`,
    festivalEdit: (id: string) => `${ROOTS.DASHBOARD}/festivals/${id}/edit`,
    manageSacred: `${ROOTS.DASHBOARD}/manage-sacred`,
    sacredNew: `${ROOTS.DASHBOARD}/manage-sacred/new`,
    sacredEdit: (id: string) => `${ROOTS.DASHBOARD}/manage-sacred/${id}/edit`,
    users: `${ROOTS.DASHBOARD}/users`,
  },
};
