import type { RemixiconComponentType } from '@remixicon/react';

import {
  RiBold,
  RiLink,
  RiItalic,
  RiAddLine,
  RiEyeLine,
  RiMicLine,
  RiSortAsc,
  RiBellLine,
  RiBikeLine,
  RiEditLine,
  RiFileLine,
  RiFlagLine,
  RiKey2Line,
  RiLockLine,
  RiMailLine,
  RiMenuLine,
  RiMoreLine,
  RiPlayLine,
  RiTimeLine,
  RiUserLine,
  RiVisaLine,
  RiWifiLine,
  RiAppleFill,
  RiCloseLine,
  RiCloudLine,
  RiGroupLine,
  RiHeartLine,
  RiHome5Line,
  RiImageLine,
  RiInboxLine,
  RiListCheck,
  RiMore2Line,
  RiPauseLine,
  RiPhoneLine,
  RiReplyLine,
  RiShareLine,
  RiToolsLine,
  RiUnderline,
  RiVideoLine,
  RiCameraLine,
  RiEyeOffLine,
  RiGithubFill,
  RiGoogleFill,
  RiIdCardLine,
  RiMapPinLine,
  RiPaypalFill,
  RiRocketLine,
  RiSearchLine,
  RiTrophyLine,
  RiUploadLine,
  RiZoomInLine,
  RiQrCodeLine,
  RiAndroidFill,
  RiArchiveLine,
  RiArrowUpLine,
  RiAttachment2,
  RiFilter3Line,
  RiGamepadLine,
  RiPaletteLine,
  RiPrinterLine,
  RiRefreshLine,
  RiWindowsFill,
  RiZoomOutLine,
  RiArrowUpSLine,
  RiBankCardLine,
  RiBookOpenLine,
  RiCalendarLine,
  RiDownloadLine,
  RiFacebookFill,
  RiFileCopyLine,
  RiFileTextLine,
  RiHospitalLine,
  RiImageAddLine,
  RiLinkedinFill,
  RiSubtractLine,
  RiSuitcaseLine,
  RiTwitterXFill,
  RiVolumeUpLine,
  RiArrowDownLine,
  RiBluetoothLine,
  RiDeleteBinLine,
  RiDragMove2Line,
  RiFileCheckLine,
  RiFileList3Line,
  RiFolderAddLine,
  RiInstagramLine,
  RiSendPlaneFill,
  RiSettings3Line,
  RiArrowDownSLine,
  RiArrowLeftSLine,
  RiArrowRightLine,
  RiFileDamageLine,
  RiFullscreenLine,
  RiPlayCircleLine,
  RiStopCircleLine,
  RiArrowRightSLine,
  RiCloseCircleLine,
  RiUploadCloudLine,
  RiInformationLine,
  RiShieldCheckLine,
  RiArrowRightUpLine,
  RiErrorWarningLine,
  RiLayoutColumnLine,
  RiShareForwardLine,
  RiShoppingCartLine,
  RiArrowLeftDownLine,
  RiNotification3Line,
  RiCheckboxCircleLine,
  RiFullscreenExitLine,
  RiMoneyDollarCircleLine,
  RiCheckboxBlankCircleLine,
} from '@remixicon/react';

export type RemixIconName = string;

type IconRule = readonly [pattern: RegExp, icon: RemixiconComponentType];

const EXACT_ICONS: Record<string, RemixiconComponentType> = {
  'socials:facebook': RiFacebookFill,
  'socials:github': RiGithubFill,
  'socials:google': RiGoogleFill,
  'socials:instagram': RiInstagramLine,
  'socials:linkedin': RiLinkedinFill,
  'socials:twitter': RiTwitterXFill,
  'mingcute:android-2-fill': RiAndroidFill,
  'mingcute:apple-fill': RiAppleFill,
  'mingcute:windows-fill': RiWindowsFill,
  'payments:mastercard': RiBankCardLine,
  'payments:paypal': RiPaypalFill,
  'payments:visa': RiVisaLine,
  'custom:drag-dots-fill': RiDragMove2Line,
  'custom:send-fill': RiSendPlaneFill,
  'custom:sidebar-fold-fill': RiLayoutColumnLine,
  'custom:sidebar-unfold-fill': RiLayoutColumnLine,
  'eva:attach-2-fill': RiAttachment2,
  'eva:link-2-fill': RiLink,
  'ic:round-format-bold': RiBold,
  'ic:round-format-italic': RiItalic,
  'ic:round-format-underlined': RiUnderline,
};

const ICON_RULES: IconRule[] = [
  [/arrow-ios-back|chevron-left/, RiArrowLeftSLine],
  [/arrow-ios-forward|chevron-right/, RiArrowRightSLine],
  [/arrow-ios-down|chevron-down|arrow-drop-down/, RiArrowDownSLine],
  [/arrow-ios-up|chevron-up/, RiArrowUpSLine],
  [/diagonal-arrow-left-down/, RiArrowLeftDownLine],
  [/diagonal-arrow-right-up|external-link/, RiArrowRightUpLine],
  [/arrowhead-left|arrow-forward-left|reply/, RiReplyLine],
  [/arrowhead-right|arrow-forward|forward/, RiArrowRightLine],
  [/arrow-downward|double-alt-arrow-down/, RiArrowDownLine],
  [/arrow-upward|double-alt-arrow-up/, RiArrowUpLine],
  [/chevron-sort|sort-by-time/, RiSortAsc],
  [/cloud-upload/, RiUploadCloudLine],
  [/cloud-download|download/, RiDownloadLine],
  [/upload|export/, RiUploadLine],
  [/import|archive-down/, RiDownloadLine],
  [/fullscreen|full-screen/, RiFullscreenLine],
  [/quit-full-screen|center-to-fit|fit-to-screen|collapse/, RiFullscreenExitLine],
  [/zoom-in/, RiZoomInLine],
  [/zoom-out/, RiZoomOutLine],
  [/search/, RiSearchLine],
  [/close-circle|minus-circle/, RiCloseCircleLine],
  [/close/, RiCloseLine],
  [/add-folder/, RiFolderAddLine],
  [/add|cart-plus|user-plus/, RiAddLine],
  [/minimize/, RiSubtractLine],
  [/trash|delete/, RiDeleteBinLine],
  [/pen|edit|eraser/, RiEditLine],
  [/calendar/, RiCalendarLine],
  [/clock|time/, RiTimeLine],
  [/checkmark-circle|check-circle|verified-check/, RiCheckboxCircleLine],
  [/checkmark|done-all/, RiListCheck],
  [/radio-button/, RiCheckboxBlankCircleLine],
  [/users-group|team/, RiGroupLine],
  [/user-id|profile/, RiIdCardLine],
  [/user/, RiUserLine],
  [/camera|videocamera/, RiCameraLine],
  [/gallery-add/, RiImageAddLine],
  [/gallery|image/, RiImageLine],
  [/file-check/, RiFileCheckLine],
  [/duplicate|copy/, RiFileCopyLine],
  [/qr-code|qrcode/, RiQrCodeLine],
  [/file-corrupted/, RiFileDamageLine],
  [/file-text|bill-list|invoice/, RiFileTextLine],
  [/file|notes|notebook/, RiFileList3Line],
  [/book/, RiBookOpenLine],
  [/home/, RiHome5Line],
  [/bell-off/, RiBellLine],
  [/bell|notification/, RiNotification3Line],
  [/chat|message/, RiMore2Line],
  [/letter|mail/, RiMailLine],
  [/phone|smartphone/, RiPhoneLine],
  [/location|map-pin/, RiMapPinLine],
  [/shield|security/, RiShieldCheckLine],
  [/lock-password|vpn-key|keyhole/, RiKey2Line],
  [/lock/, RiLockLine],
  [/info/, RiInformationLine],
  [/danger|warning|forbidden/, RiErrorWarningLine],
  [/eye-closed/, RiEyeOffLine],
  [/eye/, RiEyeLine],
  [/settings/, RiSettings3Line],
  [/menu-dots|more-horizontal/, RiMoreLine],
  [/more-vertical/, RiMore2Line],
  [/menu|view-list/, RiMenuLine],
  [/list|view-module|view-quilt/, RiListCheck],
  [/filter/, RiFilter3Line],
  [/play-circle|video-frame-play/, RiPlayCircleLine],
  [/play/, RiPlayLine],
  [/pause/, RiPauseLine],
  [/stop/, RiStopCircleLine],
  [/restart|activity/, RiRefreshLine],
  [/send/, RiSendPlaneFill],
  [/share/, RiShareLine],
  [/multiple-forward/, RiShareForwardLine],
  [/heart|like/, RiHeartLine],
  [/dislike/, RiHeartLine],
  [/star|award|cup|confetti/, RiTrophyLine],
  [/flag/, RiFlagLine],
  [/medical/, RiHospitalLine],
  [/wad-of-money|payment|bank-card/, RiMoneyDollarCircleLine],
  [/cart/, RiShoppingCartLine],
  [/box|minimalistic|case|suitcase/, RiSuitcaseLine],
  [/inbox/, RiInboxLine],
  [/archive/, RiArchiveLine],
  [/cloud|weather/, RiCloudLine],
  [/palette|pallete|color/, RiPaletteLine],
  [/microphone/, RiMicLine],
  [/volume/, RiVolumeUpLine],
  [/printer/, RiPrinterLine],
  [/gamepad/, RiGamepadLine],
  [/bicycle/, RiBikeLine],
  [/rocket/, RiRocketLine],
  [/bluetooth/, RiBluetoothLine],
  [/wifi/, RiWifiLine],
  [/monitor|tv|video/, RiVideoLine],
  [/tools|dumbbell|atom|skill/, RiToolsLine],
];

export const allIconNames: string[] = [];

export function getRemixIcon(icon: RemixIconName): RemixiconComponentType {
  const exactIcon = EXACT_ICONS[icon];

  if (exactIcon) {
    return exactIcon;
  }

  const rule = ICON_RULES.find(([pattern]) => pattern.test(icon));

  return rule?.[1] ?? RiFileLine;
}
