import type { NavSectionProps } from 'src/components/nav-section';
import {
  RiArticleLine,
  RiBuildingLine,
  RiCalendarLine,
  RiDashboardLine,
  RiImageLine,
  RiMailLine,
  RiMenuLine,
  RiShieldStarLine,
  RiTeamLine,
} from 'src/components/remix-icon';
import { paths } from 'src/routes/paths';

export const navData: NavSectionProps['data'] = [
  {
    subheader: 'ภาพรวม',
    items: [
      {
        title: 'หน้าหลัก',
        path: paths.dashboard.root,
        icon: <RiDashboardLine />,
        featureKey: 'dashboard',
      },
      {
        title: 'จัดการหน้าคงที่',
        path: paths.dashboard.pages,
        icon: <RiArticleLine />,
        featureKey: 'pages',
        deep: true,
      },
      {
        title: 'จัดการเมนู',
        path: paths.dashboard.menus,
        icon: <RiMenuLine />,
        featureKey: 'pages',
        deep: true,
      },
      {
        title: 'จัดการข่าวสาร/กิจกรรม',
        path: paths.dashboard.activity,
        icon: <RiCalendarLine />,
        featureKey: 'activities',
        deep: true,
      },
      {
        title: 'จัดการสถาปัตย์และสิ่งสำคัญ',
        path: paths.dashboard.architectures,
        icon: <RiBuildingLine />,
        featureKey: 'architectures',
        deep: true,
      },
      {
        title: 'จัดการทำเนียบวัด',
        path: paths.dashboard.directory,
        icon: <RiTeamLine />,
        featureKey: 'directory',
        deep: true,
      },
      {
        title: 'จัดการผู้นำชุมชน',
        path: paths.dashboard.communityLeaders,
        icon: <RiTeamLine />,
        featureKey: 'community_leaders',
        deep: true,
      },
      {
        title: 'จัดการแบนเนอร์',
        path: paths.dashboard.banners,
        icon: <RiImageLine />,
        featureKey: 'banners',
        deep: true,
      },
      {
        title: 'จัดการแบนเนอร์ป๊อปอัป',
        path: paths.dashboard.popupBanners,
        icon: <RiImageLine />,
        featureKey: 'banners',
        deep: true,
      },
      {
        title: 'จัดการงานประเพณี',
        path: paths.dashboard.festivals,
        icon: <RiCalendarLine />,
        featureKey: 'festivals',
        deep: true,
      },
      {
        title: 'จัดการบทความ',
        path: paths.dashboard.blogs,
        icon: <RiArticleLine />,
        featureKey: 'blogs',
        deep: true,
      },
      {
        title: 'จัดการธรรมะ',
        path: paths.dashboard.dharmas,
        icon: <RiArticleLine />,
        featureKey: 'dharmas',
        deep: true,
      },
      {
        title: 'จัดการข้อความติดต่อ',
        path: paths.dashboard.contacts,
        icon: <RiMailLine />,
        featureKey: 'contacts',
        deep: true,
      },
      {
        title: 'จัดการสิ่งศักดิ์สิทธิ์',
        path: paths.dashboard.manageSacred,
        icon: <RiShieldStarLine />,
        featureKey: 'sacred',
        deep: true,
      },
      {
        title: 'สมาชิกวัด',
        path: paths.dashboard.members,
        icon: <RiTeamLine />,
        featureKey: 'members',
        deep: true,
      },
    ],
  },
  {
    subheader: 'ผู้ดูแลระบบ',
    items: [
      {
        title: 'จัดการผู้ใช้งาน',
        path: paths.dashboard.users,
        icon: <RiTeamLine />,
        roles: ['super_admin'],
        deep: true,
      },
      {
        title: 'จัดการวัดและสิทธิ์',
        path: paths.dashboard.temples,
        icon: <RiBuildingLine />,
        roles: ['super_admin'],
        deep: true,
      },
      {
        title: 'จัดการธีมเว็บไซต์',
        path: paths.dashboard.templates,
        icon: <RiImageLine />,
        roles: ['super_admin'],
        deep: true,
      },
    ],
  },
];
